SELECT  id,
        username,
        name,
        email,
        uid,
        facebookId,
        gmailId,
        appleId,
        accountType,
        photo,
        bigPhoto,
        messagingToken,
        points,
        grade,
        coins,
        coins_weekly,
        coins_monthly,
        lastOpen,
        level,
        levelPercent,
        wins,
        loses,
        isVip,
        active,
        blocked,
        remember_token,
        created_at,
        updated_at,
        seeks,
        subscription_date,
        gems,
        gender,
        birth_date

        FROM customers;